import { useEffect, useRef, useState } from 'react';
import { useLang } from '../../i18n';
import { reducedMotion } from '../../lib/motion';
const words={en:['Drag to orbit the temple.','Separate the three storeys','Roof plan','Front perspective','Turntable','Closer','Further','3D needs WebGL. The facade and architectural notes remain available.'],ne:['मन्दिर घुमाउन तान्नुहोस्।','तीन तला छुट्याउनुहोस्','छानाको योजना','अगाडिको परिप्रेक्ष्य','घुमाउनुहोस्','नजिक','टाढा','थ्रीडीका लागि WebGL चाहिन्छ। अगाडिको दृश्य र वास्तुकलाका टिप्पणी उपलब्ध छन्।'],mai:['मन्दिर घुमाबय लेल खींचू।','तीन मंजिल अलग करू','छतक नक्शा','सोझाँक दृश्य','घुमाउ','लग','दूर','थ्रीडी लेल WebGL चाही। सोझाँक दृश्य आ वास्तुकलाक टिप्पणी उपलब्ध अछि।']};
export default function TempleStudy({selected}){
  const l=words[useLang()],canvas=useRef(null),api=useRef(null),[explode,setExplode]=useState(false),[plan,setPlan]=useState(false),[rotate,setRotate]=useState(false),[failed,setFailed]=useState(false);
  useEffect(()=>{let alive=true,scene,ro,io;import('../../three/TempleScene').then(({createTempleScene})=>{if(!alive)return;try{scene=createTempleScene(canvas.current);api.current=scene;ro=new ResizeObserver(()=>{const r=canvas.current.getBoundingClientRect();scene.resize(r.width,r.height);});ro.observe(canvas.current);io=new IntersectionObserver(([entry])=>scene.active(entry.isIntersecting));io.observe(canvas.current);}catch{setFailed(true);}}).catch(()=>{if(alive)setFailed(true);});return()=>{alive=false;ro?.disconnect();io?.disconnect();scene?.dispose();api.current=null;};},[]);
  useEffect(()=>{api.current?.select(selected);},[selected]);
  return <div className="temple-study"><canvas ref={canvas} role="img" aria-label={l[0]}/>{failed&&<p className="temple-study-fallback">{l[7]}</p>}<p className="temple-study-hint">{l[0]}</p><div className="temple-study-tools"><button type="button" className="chip" aria-pressed={explode} onClick={()=>{setExplode(!explode);api.current?.explode(!explode);}}>{l[1]}</button><button type="button" className="chip" aria-pressed={plan} onClick={()=>{setPlan(!plan);api.current?.view(!plan);}}>{plan?l[3]:l[2]}</button><button type="button" className="chip" aria-pressed={rotate} onClick={()=>{setRotate(!rotate);api.current?.rotate(!rotate&&!reducedMotion());}}>{l[4]}</button><button type="button" className="chip" onClick={()=>api.current?.zoom(.88)}>{l[5]} +</button><button type="button" className="chip" onClick={()=>api.current?.zoom(1.12)}>{l[6]} −</button></div></div>;
}
