import { useRef, useState } from 'react';
import { BellIcon } from '@phosphor-icons/react';
import { useLang } from '../../i18n';
import { sound } from '../../lib/sound';
import { findEgg } from '../../lib/eggs';
import './nepal.css';
const copy={
 en:{title:'The domes that mean home.',lede:'Janaki Mandir, in the heart of Janakpur. A tribute to Sita, to Mithila, and to the place this journey began.',views:['Facade','Architectural study'],bell:'Ring the temple bell',note:'Explore the markers. This illustration follows the temple’s ornate facade; it is an artistic interpretation, not a measured survey.',source:'Read at Nepal Tourism Board',details:[['Crowned in domes','The palace-like silhouette brings Mughal influences together with local architectural traditions. The white surface is punctuated by pastel ornament and decorative balconies.'],['An arcade of arches','Repetition does the quiet work: rows of scalloped arches, columns and intricate lattice openings give the facade its rhythm.'],['A temple to Janaki','Janaki is another name for Sita, daughter of King Janak. The temple has three storeys and sixty rooms. It remains a living place of worship, not just a beautiful facade.'],['The wedding remembered','Vivah Panchami celebrates the marriage of Sita and Rama. The nearby Vivah Mandap is associated with their wedding in local tradition.'] ]},
 ne:{title:'घर सम्झाउने गुम्बजहरू।',lede:'जनकपुरको मुटुमा जानकी मन्दिर। सीता, मिथिला र यो यात्रा सुरु भएको ठाउँप्रति समर्पण।',views:['अगाडिको दृश्य','वास्तुकलाको अध्ययन'],bell:'मन्दिरको घण्टी बजाउनुहोस्',note:'चिन्हहरू छान्नुहोस्। मन्दिरको सजिएको मोहडाबाट प्रेरित कलात्मक चित्र, नापिएको सर्वेक्षण होइन।',source:'नेपाल पर्यटन बोर्डमा पढ्नुहोस्',details:[['गुम्बजको मुकुट','दरबारजस्तो आकृतिमा मुगल प्रभाव र स्थानीय वास्तुकला मिसिन्छन्। सेतो सतहमा हल्का रङका सजावट र बार्दली छन्।'],['मेहराबहरूको लय','लहरदार मेहराब, खम्बा र जालीदार झ्यालहरूको दोहोरिने क्रमले मोहडालाई लय दिन्छ।'],['जानकीको मन्दिर','राजा जनककी छोरी सीताको अर्को नाम जानकी हो। मन्दिरमा तीन तला र साठी कोठा छन्। यो जीवन्त पूजा स्थल हो।'],['विवाहको सम्झना','विवाह पञ्चमीमा सीता र रामको विवाह मनाइन्छ। नजिकको विवाह मण्डपलाई परम्परामा उनीहरूको विवाहसँग जोडिन्छ।']]},
 mai:{title:'घर मोन पड़बैत गुम्बज।',lede:'जनकपुरक हृदयमे जानकी मन्दिर। सीता, मिथिला आ यात्रा शुरू भेल ठामक लेल समर्पण।',views:['सोझाँक दृश्य','वास्तुकलाक अध्ययन'],bell:'मन्दिरक घंटी बजाउ',note:'चिह्न चुनू। मन्दिरक सजाओल मोहड़ासँ प्रेरित कलात्मक चित्र; नापल सर्वेक्षण नहि।',source:'नेपाल पर्यटन बोर्डमे पढ़ू',details:[['गुम्बजक मुकुट','दरबार सन आकृतिमे मुगल प्रभाव आ स्थानीय वास्तुकला मिलैत अछि। उज्जर सतह पर हल्का रंग आ सजाओल बरामदा अछि।'],['मेहराबक लय','मेहराब, खम्भा आ जालीदार खिड़कीक क्रम मोहड़ाकेँ लय दैत अछि।'],['जानकीक मन्दिर','राजा जनकक बेटी सीताक दोसर नाम जानकी अछि। मन्दिरमे तीन मंजिल आ साठ कोठरी अछि। ई जीवित पूजा स्थल अछि।'],['विवाहक याद','विवाह पञ्चमीमे सीता आ रामक विवाह मनाओल जाइत अछि। लगक विवाह मण्डप परम्परामे हुनक विवाहसँ जुड़ल अछि।']]}
};
const points=[[21,25],[56,56],[49,34],[74,82]];
export default function Temple(){const lang=useLang(),l=copy[lang],taps=useRef({n:0,at:0}),[study,setStudy]=useState(false),[selected,setSelected]=useState(0);const ring=()=>{const now=Date.now();taps.current.n=now-taps.current.at<1800?taps.current.n+1:1;taps.current.at=now;sound.bowl();if(taps.current.n>=3)findEgg('sita');};return <section className="section mandir" aria-labelledby="mandir-title"><div className="wrap"><div className="mandir-heading"><div><p className="t-label">JANAKPUR DHAM / MITHILA</p><h2 className="t-title" id="mandir-title">{l.title}</h2><p className="t-lede">{l.lede}</p></div><div className="mandir-toggle">{l.views.map((v,i)=><button className="chip" type="button" key={v} aria-pressed={study===!!i} onClick={()=>setStudy(!!i)}>{v}</button>)}</div></div><div className={'temple-image'+(study?' is-study':'')}><img src="/imagery/janaki.webp" alt={l.title} loading="lazy" decoding="async"/>{points.map(([x,y],i)=><button className="temple-marker" type="button" key={i} aria-label={l.details[i][0]} aria-pressed={selected===i} style={{left:x+'%',top:y+'%'}} onClick={()=>setSelected(i)}>{i+1}</button>)}<button className="mandir-bell" type="button" onClick={ring} aria-label={l.bell}><BellIcon size={26}/></button></div><div className="temple-caption" aria-live="polite"><span className="t-label">0{selected+1} / JANAKI</span><h3>{l.details[selected][0]}</h3><p>{l.details[selected][1]}</p></div><p className="t-small mandir-note">{l.note} <a href="https://ntb.gov.np/en/janaki-mandir--janakpur--dhanusha" target="_blank" rel="noreferrer">{l.source} ↗</a></p></div></section>;}
