import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { createAirliner } from '../../three/airliner';
import { useLang } from '../../i18n';
import { reducedMotion } from '../../lib/motion';
import { findEgg } from '../../lib/eggs';
import Dialog from '../ui/Dialog';
const copy={en:['Aircraft hangar','Drag to orbit. Scroll to zoom. Or choose a camera view below.','Front','Side','Above','Landing gear','Rotate','Roll once','Open aircraft hangar','The aircraft needs WebGL to be explored.'],ne:['विमानको ह्याङ्गर','घुमाउन तान्नुहोस्। ठूलो बनाउन स्क्रोल गर्नुहोस् वा तल दृश्य छान्नुहोस्।','अगाडि','छेउ','माथि','अवतरण चक्का','घुमाउनुहोस्','एकपटक रोल','विमान ह्याङ्गर खोल्नुहोस्','विमान हेर्न WebGL चाहिन्छ।'],mai:['विमानक हैंगर','घुमाबय लेल खींचू। पैघ करय लेल स्क्रोल करू वा नीचाँ दृश्य चुनू।','आगू','बगल','ऊपर','अवतरण पहिया','घुमाउ','एक बेर रोल','विमानक हैंगर खोलू','विमान देखबाक लेल WebGL चाही।']};
export default function AircraftHangar(){const l=copy[useLang()],[open,setOpen]=useState(false),[failed,setFailed]=useState(false),[gear,setGear]=useState(false),[rotate,setRotate]=useState(false),canvas=useRef(null),actions=useRef(null);
 useEffect(()=>{if(!open)return;let renderer,aircraft,controls,env,pmrem,ro,raf=0,roll=0,gearTarget=0,gearNow=0;let disposed=false;const views=[[6.5,1.3,0],[0,.3,5.2],[.01,7,.01]];
 try{renderer=new THREE.WebGLRenderer({canvas:canvas.current,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(4.8,1.3,4.8);scene.add(new THREE.HemisphereLight('#ebf1e8','#314b3f',1));const sun=new THREE.DirectionalLight('#fff6e5',3);sun.position.set(5,8,4);scene.add(sun);pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();env=pmrem.fromScene(room);room.dispose();scene.environment=env.texture;aircraft=createAirliner({accent:'#214b39'});scene.add(aircraft.group);controls=new OrbitControls(camera,canvas.current);controls.enableDamping=true;controls.minDistance=4.5;controls.maxDistance=13;controls.enablePan=false;controls.autoRotateSpeed=.8;
 const size=()=>{const el=canvas.current;if(!el)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight,false);};ro=new ResizeObserver(size);ro.observe(canvas.current);size();let last=0;
 const frame=time=>{if(disposed)return;raf=requestAnimationFrame(frame);if(document.hidden){last=time;return;}const dt=Math.min(.05,(time-last)/1000||0);last=time;gearNow=THREE.MathUtils.damp(gearNow,gearTarget,6,dt);aircraft.setGear(gearNow);aircraft.update(time/1000,{night:0,landing:gearNow});if(roll>0){const p=Math.min(1,roll);aircraft.group.rotation.x=Math.PI*2*(p*p*(3-2*p));roll+=dt/1.8;if(roll>=1){roll=0;aircraft.group.rotation.x=0;}}controls.update(dt);renderer.render(scene,camera);};raf=requestAnimationFrame(frame);
 actions.current={view:i=>{camera.position.set(...views[i]);controls.target.set(0,0,0);controls.update();},gear:value=>{gearTarget=value?1:0;},rotate:value=>{controls.autoRotate=value;},roll:()=>{roll=reducedMotion()?0:.001;findEgg('roll');}};
 aircraft.ready.catch(()=>{if(!disposed)setFailed(true);});
 }catch{setFailed(true);}
 return()=>{disposed=true;cancelAnimationFrame(raf);ro?.disconnect();controls?.dispose();aircraft?.dispose();env?.dispose();pmrem?.dispose();renderer?.dispose();actions.current=null;};
 },[open]);
 return <><button className="btn btn-ghost hero-ghost" type="button" onClick={()=>{setOpen(true);setFailed(false);setGear(false);setRotate(false);}}>{l[8]} ↗</button><Dialog open={open} onClose={()=>setOpen(false)} label={l[0]} variant="center" className="aircraft-hangar"><p className="t-label">SUVMITH AIR / A350 · INTELLIGENCE INSIDE</p><h2 className="t-title">{l[0]}</h2><p>{l[1]}</p><div className="hangar-view"><canvas ref={canvas} aria-label={l[0]} role="img"/>{failed&&<p>{l[9]}</p>}</div><div className="hangar-controls">{l.slice(2,5).map((label,i)=><button className="chip" type="button" key={i} onClick={()=>actions.current?.view(i)}>{label}</button>)}<button type="button" className="chip" aria-pressed={gear} onClick={()=>{setGear(!gear);actions.current?.gear(!gear);}}>{l[5]}</button><button type="button" className="chip" aria-pressed={rotate} onClick={()=>{setRotate(!rotate);actions.current?.rotate(!rotate);}}>{l[6]}</button><button className="chip" type="button" onClick={()=>actions.current?.roll()}>{l[7]}</button></div><p className="t-micro">A350 model by <a href="https://github.com/amvlab/aircraft-models" target="_blank" rel="noreferrer">amvlab</a> · <a href="/models/LICENSE-a350.txt">CC BY 4.0</a> · custom livery.</p></Dialog></>;
}

