import { useEffect, useState } from 'react';
import { useLang } from '../../i18n';
import { Term } from '../ui/Term';
import { virgoLines, virgoNamed, virgoField } from '../../data/kanya';
import { setGrid } from '../../lib/grid';
import { findEgg } from '../../lib/eggs';
import './kanya.css';
import './cosmos.css';
const copy={
 en:{title:'Feet on earth. Eyes on the stars.',lede:'My rashi is Kanya, an earth sign. I like the grounded part: small routines, noticing details and keeping things in order. The stars are an invitation to look up.',tabs:['Star chart','Deep field','A message to space'],chart:'Explore Virgo',hint:'Select a star. Zoom into the chart, or press G to connect the constellation.',lines:'Connect the stars',zoom:'Chart magnification',habit:'Little things about me.',turn:'Turn over',label:'A small habit',source:'Explore at NASA',record:'The Voyager Golden Record',recordText:'In 1977, both Voyager spacecraft left Earth carrying a gold-plated record of pictures, voices and sounds. A hello to whoever might listen.',hello:'A hello, across the dark.',helloText:'Greetings in 55 languages, music and the sounds of Earth. An interstellar mixtape, made before we knew who would hear it.',field:'Beyond the stars: galaxies.',fieldText:'The Virgo Cluster holds galaxies far beyond our foreground stars. M87 is a giant elliptical galaxy; M60 is another luminous neighbour. Choose a destination.',composed:'An illustrated deep field; the star chart uses celestial coordinates.',habits:[['Window seat','Will negotiate for a window seat, then spend the whole flight staring outside.'],['Green, quietly','Favourite colour: green. Apparently it has made its way into every button.'],['A little order','Straightens a crooked thing before noticing he has done it.'],['Overthinking','Can plan a whole route and still overthink a simple “hi”.'],['Chiya time','Some conversations need another cup before they need an answer.'],['Keeps the little things','A view, a ticket, a funny line from a friend. Small things become souvenirs.'],['Single, currently','Seat 1B is available. Kalyani, this is a very subtle announcement.'],['Curious by default','A quick question has a habit of becoming a very long rabbit hole.']]},
 ne:{title:'खुट्टा धरतीमा। आँखा तारातिर।',lede:'मेरो राशि कन्या, पृथ्वी तत्त्वको राशि। साना दिनचर्या, मसिना कुरा याद गर्ने र चिज मिलाउने बानी मन पर्छ। ताराहरू माथि हेर्ने निम्तो हुन्।',tabs:['तारा नक्सा','गहिरो अन्तरिक्ष','अन्तरिक्षलाई सन्देश'],chart:'कन्याको आकाश',hint:'तारा छान्नुहोस्। नक्सा ठूलो बनाउनुहोस् वा G थिचेर ताराहरू जोड्नुहोस्।',lines:'ताराहरू जोड्नुहोस्',zoom:'नक्साको विस्तार',habit:'मेरा साना बानीहरू।',turn:'पल्टाउनुहोस्',label:'एउटा सानो बानी',source:'NASA मा हेर्नुहोस्',record:'भ्वायजरको सुनौलो रेकर्ड',recordText:'सन् १९७७ मा दुवै भ्वायजर यानले पृथ्वीका तस्बिर, आवाज र ध्वनि बोकेको सुनको लेप भएको रेकर्ड लगे। जसले सुने पनि, नमस्कार।',hello:'अँध्यारो पारि एउटा नमस्कार।',helloText:'५५ भाषाका अभिवादन, संगीत र पृथ्वीका ध्वनि। कसले सुन्ला थाहा नहुँदै बनाइएको अन्तरिक्षको संकलन।',field:'तारापारि: आकाशगंगाहरू।',fieldText:'कन्या समूहमा नजिकका ताराभन्दा धेरै परका आकाशगंगा छन्। M87 विशाल अण्डाकार आकाशगंगा हो; M60 अर्को चम्किलो छिमेकी। गन्तव्य छान्नुहोस्।',composed:'गहिरो अन्तरिक्षको कलात्मक दृश्य; तारा नक्सामा खगोलीय निर्देशाङ्क छन्।',habits:[['झ्यालको सिट','झ्यालको सिट माग्छु अनि उडानभरि बाहिर हेरिरहन्छु।'],['शान्त हरियो','मन पर्ने रङ हरियो। बिस्तारै सबै बटनसम्म आइपुग्यो।'],['अलिकति क्रम','बाङ्गो चिज थाहै नपाई सीधा पारिदिन्छु।'],['धेरै सोचाइ','पूरै बाटोको योजना बनाउन सक्छु तर एउटा “हाई” मा अड्किन्छु।'],['चिया समय','कतिपय कुराकानीलाई उत्तरभन्दा अर्को कप चाहिन्छ।'],['साना सम्झना','दृश्य, टिकट, साथीको रमाइलो कुरा। साना चिज सम्झना बन्छन्।'],['अहिले एक्लै','सिट 1B खाली छ। कल्याणी, यो निकै सूक्ष्म घोषणा हो।'],['सधैँ जिज्ञासु','सानो प्रश्नले प्रायः लामो खोजको बाटो खोल्छ।']]},
 mai:{title:'पएर धरती पर। आँखि तारा दिस।',lede:'हमर राशि कन्या, पृथ्वी तत्त्वक राशि। छोट दिनचर्या, बारीक बात देखब आ चीज मिलायब नीक लगैत अछि। तारा ऊपर देखबाक निमन्त्रण अछि।',tabs:['तारा नक्शा','गहिर अन्तरिक्ष','अन्तरिक्ष लेल सन्देश'],chart:'कन्याक आकाश',hint:'तारा चुनू। नक्शा पैघ करू वा G दबा कऽ तारा जोड़ू।',lines:'तारा जोड़ू',zoom:'नक्शाक विस्तार',habit:'हमर छोट आदति सभ।',turn:'पलटू',label:'एकटा छोट आदति',source:'NASA मे देखू',record:'वॉयजरक सुनहुल रेकॉर्ड',recordText:'१९७७ मे दुनू वॉयजर यान पृथ्वीक चित्र, आवाज आ ध्वनि लऽ कऽ गेल। जे सुनय, तकरा प्रणाम।',hello:'अन्हारक पार एकटा प्रणाम।',helloText:'५५ भाषाक अभिवादन, संगीत आ पृथ्वीक ध्वनि। बिना श्रोता जानने बनाओल अन्तरिक्षक संकलन।',field:'ताराक पार: आकाशगंगा।',fieldText:'कन्या समूह मे नजदीकक तारासँ बहुत दूरक आकाशगंगा अछि। M87 विशाल अण्डाकार आकाशगंगा अछि; M60 दोसर चमकैत पड़ोसी। गन्तव्य चुनू।',composed:'अन्तरिक्षक कलात्मक दृश्य; तारा नक्शा खगोलीय निर्देशाङ्कसँ बनल अछि।',habits:[['खिड़कीक सीट','खिड़कीक सीट मांगि कऽ पूरा उड़ान बाहर देखैत रहैत छी।'],['शान्त हरियर','मनपसन्द रंग हरियर। आब सब बटन धरि पहुँचि गेल।'],['कनेक क्रम','टेढ़ चीज बिना सोचने सीधा कऽ दैत छी।'],['बेसी सोचब','पूरा रस्ताक योजना बनबैत छी मुदा एकटा “हाई” पर अटकैत छी।'],['चायक समय','किछु गप्पकेँ उत्तरसँ पहिने दोसर कप चाही।'],['छोट याद','दृश्य, टिकट, मित्रक मजेदार बात। छोट चीज याद बनैत अछि।'],['एखन अकेला','सीट 1B खाली अछि। कल्याणी, ई बहुत सूक्ष्म घोषणा अछि।'],['सदिखन उत्सुक','छोट प्रश्न प्रायः लम्बा खोज बनि जाइत अछि।']]}
};
const px=ra=>(232-ra)*10,py=dec=>(18-dec)*10;
const field=Array.from({length:210},(_,i)=>({x:(i*137.507)%640,y:(i*i*13.17)%420,r:.35+(i%5)*.15}));
const stars={Spica:'α Virginis / Chitra',Porrima:'γ Virginis / Binary',Vindemiatrix:'ε Virginis',Zavijava:'β Virginis',Heze:'ζ Virginis'};
function Habit({item,index,l}){const [open,setOpen]=useState(false);return <li className="trait"><button type="button" className={'trait-inner'+(open?' is-flipped':'')} aria-pressed={open} aria-label={item[0]+'. '+(open?item[1]:l.turn)} onClick={()=>setOpen(!open)}><span className="trait-face trait-front" aria-hidden={open}><span className="trait-n">0{index+1}</span><span className="trait-name">{item[0]}</span><span className="trait-cta">{l.turn}</span></span><span className="trait-face trait-back" aria-hidden={!open}><span className="trait-ev-label">{l.label}</span><span className="trait-ev">{item[1]}</span></span></button></li>;}
export default function Cosmos(){
 const lang=useLang(),l=copy[lang], [tab,setTab]=useState(0),[lines,setLines]=useState(true),[zoom,setZoom]=useState(1),[selected,setSelected]=useState('Spica'),[galaxy,setGalaxy]=useState('M87'),[record,setRecord]=useState(false),[visited,setVisited]=useState([0]);
 useEffect(()=>{const on=e=>setLines(e.detail);document.addEventListener('ss-star-chart',on);return()=>document.removeEventListener('ss-star-chart',on);},[]);
 const switchTab=i=>{setTab(i);setVisited(v=>{const n=[...new Set([...v,i])];if(n.length===3)findEgg('cosmos');return n;});};
 return <section id="kanya" className="kanya cosmos" aria-labelledby="kanya-title"><div className="kanya-sky" aria-hidden="true"/><div className="wrap kanya-content">
  <header className="cosmos-head"><p className="t-label"><Term id="kanya">कन्या / KANYA</Term> · {lang==='en'?'EARTH SIGN':lang==='ne'?'पृथ्वी तत्त्व':'पृथ्वी तत्त्व'}</p><h2 className="t-display" id="kanya-title">{l.title}</h2><p className="t-lede">{l.lede}</p></header>
  <div className="cosmos-tabs" role="group" aria-label={l.chart}>{l.tabs.map((name,i)=><button type="button" className="chip" aria-pressed={tab===i} onClick={()=>switchTab(i)} key={name}>{name}<span aria-hidden="true">{visited.includes(i)?' ·':''}</span></button>)}</div>
  <div className="observatory"><div className="cosmos-window"><svg viewBox="0 0 640 420" role="img" aria-label={tab===0?l.chart:tab===1?l.field:l.record} className="cosmos-space"><defs><radialGradient id="cosmos-glow"><stop stopColor="#a3d9b7" stopOpacity=".4"/><stop offset="1" stopColor="#a3d9b7" stopOpacity="0"/></radialGradient></defs>{field.map((s,i)=><circle key={i} cx={s.x} cy={s.y} r={s.r} fill="#dae7ef" opacity={.35+(i%7)*.08}/>)}
    {tab===0&&<g transform={'translate(320 210) scale('+zoom+') translate(-320 -210)'}>{virgoField.map(([ra,dec,mag],i)=><circle key={i} cx={px(ra)} cy={py(dec)} r={Math.max(.6,3.6-mag*.62)} fill="#dfe4ff"/>)}{lines&&virgoLines.map((seg,i)=><path key={i} className="virgo-line" d={seg.map(([ra,dec],j)=>(j?'L':'M')+px(ra)+' '+py(dec)).join(' ')}/>)}{virgoNamed.map(s=><g key={s.name}><circle cx={px(s.ra)} cy={py(s.dec)} r={selected===s.name?30:14} fill="url(#cosmos-glow)"/><circle cx={px(s.ra)} cy={py(s.dec)} r={selected===s.name?5:3} fill="#fff"/><text x={px(s.ra)+10} y={py(s.dec)-9} className="virgo-label">{s.name}</text></g>)}</g>}
    {tab===1&&<g transform="translate(320 210)"><ellipse rx={galaxy==='M87'?115:80} ry={galaxy==='M87'?95:65} fill="url(#cosmos-glow)"/>{Array.from({length:270},(_,i)=>{const a=i*2.4,r=Math.sqrt(i)*5;return <circle key={i} cx={Math.cos(a)*r} cy={Math.sin(a)*r*.65} r={.7+(1-i/270)*1.7} fill="#f9e8cf" opacity={.25+(1-i/270)*.6}/>;})}<circle r="7" fill="#fff7e4"/>{galaxy==='M87'&&<path d="M0 0L-122 -60" stroke="#b6d4ff" strokeWidth="2" opacity=".5"/>}</g>}
    {tab===2&&<g transform="translate(320 210)"><circle r="126" fill="#ae8133"/><circle r="120" fill="#c99c46"/>{Array.from({length:35},(_,i)=><circle key={i} r={40+i*2.25} fill="none" stroke={i%2?'#b28436':'#ead098'} strokeWidth=".6"/>)}<circle r="37" fill="#152923"/><circle r="4" fill="#f5dfaa"/><path d="M-14 -22H14M0 -22V16M-15 20H15" stroke="#e8c987" fill="none"/></g>}
   </svg></div><div className="cosmos-panel">
    {tab===0?<><p className="t-label">VIRGO / 01</p><h3>{selected}</h3><p className="cosmos-coordinate">{stars[selected]}</p><div className="star-choices">{virgoNamed.map(s=><button className="chip" type="button" key={s.name} aria-pressed={selected===s.name} onClick={()=>setSelected(s.name)}>{s.name}</button>)}</div><label>{l.zoom}<input type="range" min="1" max="1.5" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><button type="button" className="btn btn-ghost" aria-pressed={lines} onClick={()=>{setLines(!lines);setGrid(!lines);}}>{l.lines}</button><p className="t-small">{l.hint}</p></>:
     tab===1?<><p className="t-label">VIRGO CLUSTER / 02</p><h3>{l.field}</h3><p>{l.fieldText}</p><div className="star-choices">{['M87','M60'].map(g=><button className="chip" key={g} type="button" aria-pressed={galaxy===g} onClick={()=>setGalaxy(g)}>{g}</button>)}</div><a href={galaxy==='M60'?'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-60/':'https://science.nasa.gov/asset/hubble/compass-file-and-scale-for-virgo-cluster-galaxies/'} target="_blank" rel="noreferrer">{l.source} ↗</a><p className="t-small">{l.composed}</p></>:
     <><p className="t-label">VOYAGER / 03</p><h3>{record?l.hello:l.record}</h3><p>{record?l.helloText:l.recordText}</p><button type="button" className="btn btn-accent" aria-pressed={record} onClick={()=>{setRecord(!record);findEgg('voyager');}}>{record?l.record:l.hello}</button><a href="https://science.nasa.gov/mission/voyager/golden-record-contents/" target="_blank" rel="noreferrer">{l.source} ↗</a></>}
   </div></div><h3 className="traits-title">{l.habit}</h3><ul className="traits">{l.habits.map((item,i)=><Habit key={i} item={item} index={i} l={l}/>)}</ul>
 </div></section>;
}
