import React, { useState } from 'react';
import { BookOpen, CalendarDays, ChevronDown, Lightbulb } from 'lucide-react';
import { glossaryTerms, nowEntries } from '../data/portfolioData';

export default function NowAndGlossary() {
  const [open, setOpen] = useState(0);
  return <>
    <section id="now" className="relative py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto"><div className="glass-panel rounded-3xl p-6 sm:p-9 border border-purple-500/20"><div className="flex items-center gap-2 text-xs font-mono text-purple-300 mb-3"><CalendarDays className="w-4 h-4" /> NOW / BUILD LOG</div><h2 className="text-3xl font-bold text-white">What I’m doing, in a few honest lines.</h2><p className="text-slate-400 text-sm mt-2">A lightweight public diary for weekly notes, monthly reflections, and what’s next.</p><div className="mt-7 grid md:grid-cols-2 gap-4">{nowEntries.map((entry) => <article key={entry.label} className="rounded-2xl p-5 bg-slate-950/60 border border-slate-800"><span className="text-[11px] uppercase font-mono text-cyan-300">{entry.date} · {entry.label}</span><p className="text-slate-200 mt-3 leading-relaxed">{entry.text}</p></article>)}</div><p className="mt-5 text-xs text-slate-500">Update <code className="text-cyan-300">nowEntries</code> in portfolioData.js whenever you want to post a new note.</p></div></section>
    <section id="glossary" className="relative py-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto"><div className="text-center mb-9"><div className="inline-flex items-center gap-2 text-xs font-mono text-cyan-300"><BookOpen className="w-4 h-4" /> PLAIN-ENGLISH EXPLAINER</div><h2 className="text-3xl font-bold text-white mt-3">The ideas, without the gatekeeping.</h2><p className="text-slate-400 text-sm mt-2">Tap a term anywhere in the work, or start here.</p></div><div className="space-y-2">{glossaryTerms.map((item, index) => <article key={item.term} className="glass-card rounded-xl border-slate-800"><button onClick={() => setOpen(open === index ? -1 : index)} className="w-full flex items-center justify-between p-4 text-left"><span className="font-medium text-slate-100">{item.term}</span><ChevronDown className={`w-4 h-4 text-cyan-300 transition-transform ${open === index ? 'rotate-180' : ''}`} /></button>{open === index && <p className="px-4 pb-4 text-sm leading-relaxed text-slate-300">{item.definition}</p>}</article>)}</div><div className="mt-6 flex gap-2 items-start text-xs text-slate-400"><Lightbulb className="w-4 h-4 text-amber-300 shrink-0" />The research cards link into this section so technical language stays optional, not a barrier.</div></section>
  </>;
}
