import { useRef,useState } from 'react';
import { contextImage } from '../../lib/imagery';
import { useWorld,formatNptClock } from '../../lib/world';
import { useLang } from '../../i18n';
export default function Postcard(){
  const world=useWorld(),lang=useLang(),canvas=useRef(null),[message,setMessage]=useState('Wish you were here.'),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
  const p=contextImage('postcard-janaki');
  const l={en:['A postcard from Janakpur.','Leave yourself a little souvenir. Add a line and save your postcard.','Your message','Save postcard','Drawing…','Postcard ready.','Could not draw the postcard. Try again.'],ne:['जनकपुरको पोस्टकार्ड।','सानो सम्झना लैजानुहोस्। एउटा सन्देश लेखेर पोस्टकार्ड बचत गर्नुहोस्।','तपाईंको सन्देश','पोस्टकार्ड बचत','बनाउँदैछु…','पोस्टकार्ड तयार।','पोस्टकार्ड बनेन। फेरि प्रयास गर्नुहोस्।'],mai:['जनकपुरक पोस्टकार्ड।','एकटा छोट सन याद लऽ जाउ। सन्देश लिखि क पोस्टकार्ड बचाउ।','अहाँक सन्देश','पोस्टकार्ड बचाउ','बनबैत छी…','पोस्टकार्ड तैयार।','पोस्टकार्ड नहि बनल। फेर प्रयास करू।']}[lang];
  const save=async()=>{setBusy(true);setStatus('');try{await document.fonts.ready;const c=canvas.current;c.width=1400;c.height=1000;const ctx=c.getContext('2d');ctx.fillStyle='#f2eee6';ctx.fillRect(0,0,c.width,c.height);if(p){const img=new Image();img.src=p.src;await img.decode();const s=Math.max(1280/img.width,580/img.height);ctx.save();ctx.beginPath();ctx.rect(60,60,1280,580);ctx.clip();ctx.drawImage(img,60+(1280-img.width*s)/2,60+(580-img.height*s)/2,img.width*s,img.height*s);ctx.restore();}ctx.fillStyle='#24533e';ctx.font='bold 24px sans-serif';ctx.fillText('JANAKPUR DHAM / NEPAL',60,695);ctx.fillStyle='#292b28';ctx.font='36px "Noto Sans Devanagari Variable", sans-serif';const words=message.split(' ');let line='',y=760;for(const word of words){if(ctx.measureText(line+word).width>1210){ctx.fillText(line,60,y);line='';y+=48;}line+=word+' ';}ctx.fillText(line,60,y);ctx.font='22px monospace';ctx.fillStyle='#74766f';ctx.fillText(`${world.bs.en} / ${formatNptClock(world.date)} NPT`,60,930);ctx.fillText('shuvamsingh.com.np',960,930);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw new Error('export');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Janakpur-postcard.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(l[5]);}catch{setStatus(l[6]);}finally{setBusy(false);}};
  return <article className="magic-card card"><p className="t-label">04 / POST FROM HOME</p><h3 className="t-title">{l[0]}</h3><p>{l[1]}</p><div className="postcard-preview">{p&&<img src={p.src} alt="Janaki Mandir" loading="lazy"/>}<p>{message}</p><small>JANAKPUR / SS2504</small></div><label className="sr-only" htmlFor="postcard-message">{l[2]}</label><input id="postcard-message" className="input" value={message} onChange={e=>setMessage(e.target.value)} maxLength={120}/><button className="btn btn-ghost btn-sm" type="button" disabled={busy} onClick={save}>{busy?l[4]:l[3]}</button><p className="magic-status" role="status">{status}</p><canvas ref={canvas} hidden/></article>;
}
