// Hallucination Hunter statements, in English, Nepali and Maithili.
// Every "true" statement is checkable against the site's own data
// (src/data/*) or plain, well-known references. The false ones are
// plausible hallucinations, each with a one-line correction.
// Kept here (inside the lazily loaded game chunk) rather than in the main
// i18n dictionary, so the page does not ship these until the game is opened.
//
// level: 1 easy, 2 medium, 3 hard. topic: nepal | janakpur | aviation | ai | shuvam

export const FACTS = [
  {
    id: 'npt',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'Nepal Standard Time is UTC+5:45.', why: 'One of the very few time zones with a 45-minute offset.' },
    ne: { s: 'नेपालको मानक समय UTC+5:45 हो।', why: '४५ मिनेटको फरक भएका संसारका थोरै समय क्षेत्रमध्ये एक।' },
    mai: { s: 'नेपालक मानक समय UTC+5:45 अछि।', why: '४५ मिनटक अन्तर बला दुनियाँक गिनल चुनल समय क्षेत्र मे सँ एक।' },
  },
  {
    id: 'npt-india',
    truth: false,
    level: 1,
    topic: 'nepal',
    en: { s: 'Nepal uses the same time zone as India, UTC+5:30.', why: 'Nepal is UTC+5:45, fifteen minutes ahead of India.' },
    ne: { s: 'नेपालले भारतकै समय क्षेत्र UTC+5:30 प्रयोग गर्छ।', why: 'नेपाल UTC+5:45 मा छ, भारतभन्दा १५ मिनेट अगाडि।' },
    mai: { s: 'नेपाल भारतेक समय क्षेत्र UTC+5:30 प्रयोग करैत अछि।', why: 'नेपाल UTC+5:45 पर अछि, भारत सँ १५ मिनट आगाँ।' },
  },
  {
    id: 'flag',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'Nepal’s flag is the only national flag that is not a rectangle.', why: 'Two stacked pennants, with a moon and a sun.' },
    ne: { s: 'नेपालको झन्डा आयताकार नभएको संसारको एक मात्र राष्ट्रिय झन्डा हो।', why: 'दुई त्रिकोण एकमाथि अर्को, चन्द्र र सूर्यसहित।' },
    mai: { s: 'नेपालक झंडा दुनियाँक एकमात्र राष्ट्रीय झंडा अछि जे आयताकार नहि अछि।', why: 'दू टा त्रिकोण एक पर एक, चान आ सूर्य संग।' },
  },
  {
    id: 'everest',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'Sagarmatha (Everest) was re-measured in 2020 at 8,848.86 m.', why: 'Nepal and China announced the new height together.' },
    ne: { s: 'सगरमाथाको उचाइ २०२० मा पुनः नापिँदा ८,८४८.८६ मिटर भयो।', why: 'नेपाल र चीनले नयाँ उचाइ सँगै घोषणा गरे।' },
    mai: { s: 'सगरमाथाक ऊँचाइ २०२० मे फेर सँ नापल गेल: ८,८४८.८६ मिटर।', why: 'नेपाल आ चीन मिलि कऽ नव ऊँचाइ घोषणा केलक।' },
  },
  {
    id: 'everest-9000',
    truth: false,
    level: 1,
    topic: 'nepal',
    en: { s: 'Everest is exactly 9,000 m tall.', why: 'It is 8,848.86 m. Suspiciously round numbers are a classic hallucination tell.' },
    ne: { s: 'सगरमाथा ठ्याक्कै ९,००० मिटर अग्लो छ।', why: '८,८४८.८६ मिटर हो। शंकास्पद गोल अंक मनगढन्ते उत्तरको पुरानो संकेत हो।' },
    mai: { s: 'सगरमाथा ठीक ९,००० मिटर ऊँच अछि।', why: 'ई ८,८४८.८६ मिटर अछि। शंका लगबय बला गोल अंक मनगढ़न्त उत्तरक पुरान लक्षण थिक।' },
  },
  {
    id: 'sagarmatha-border',
    truth: true,
    level: 2,
    topic: 'nepal',
    en: { s: 'Sagarmatha sits on Nepal’s northern border with China.', why: 'Which is why the 2020 measurement was a joint Nepal and China survey.' },
    ne: { s: 'सगरमाथा नेपालको उत्तरी सिमानामा, चीनसँग जोडिएर छ।', why: 'त्यसैले २०२० को नापी नेपाल र चीनको संयुक्त सर्वेक्षण थियो।' },
    mai: { s: 'सगरमाथा नेपालक उत्तरी सीमा पर, चीन सँ सटल अछि।', why: 'तेँ २०२० क नापी नेपाल आ चीनक संयुक्त सर्वेक्षण छल।' },
  },
  {
    id: 'bs',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'The Bikram Sambat calendar runs about 56 years and 8 months ahead of the Gregorian one.', why: 'That is why it is already 2083 in Nepal.' },
    ne: { s: 'विक्रम संवत् ग्रेगोरियन पात्रोभन्दा करिब ५६ वर्ष ८ महिना अगाडि चल्छ।', why: 'त्यसैले नेपालमा अहिले नै २०८३ साल चलिरहेको छ।' },
    mai: { s: 'विक्रम संवत् ग्रेगोरियन पतरा सँ करीब ५६ बरख ८ मास आगाँ चलैत अछि।', why: 'तेँ नेपाल मे एखन २०८३ साल चलि रहल अछि।' },
  },
  {
    id: 'bs-behind',
    truth: false,
    level: 2,
    topic: 'nepal',
    en: { s: 'Bikram Sambat runs behind the Gregorian calendar, so in Nepal it is still the 1960s.', why: 'It runs ahead: it is 2083 BS right now.' },
    ne: { s: 'विक्रम संवत् ग्रेगोरियनभन्दा पछाडि छ, त्यसैले नेपालमा अझै १९६० को दशक चलिरहेछ।', why: 'यो अगाडि छ: अहिले वि.सं. २०८३ हो।' },
    mai: { s: 'विक्रम संवत् ग्रेगोरियन सँ पाछाँ अछि, तेँ नेपाल मे एखनो १९६० क दशक चलि रहल अछि।', why: 'ई आगाँ अछि: एखन वि.सं. २०८३ अछि।' },
  },
  {
    id: 'seasons',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'The Nepali calendar has six seasons.', why: 'Basanta, Grishma, Barsha, Sharad, Hemanta and Shishir.' },
    ne: { s: 'नेपाली पात्रोमा छवटा ऋतु हुन्छन्।', why: 'वसन्त, ग्रीष्म, वर्षा, शरद, हेमन्त र शिशिर।' },
    mai: { s: 'नेपाली पतरा मे छह टा ऋतु होइत अछि।', why: 'वसन्त, ग्रीष्म, वर्षा, शरद, हेमन्त आ शिशिर।' },
  },
  {
    id: 'seasons-four',
    truth: false,
    level: 1,
    topic: 'nepal',
    en: { s: 'The Nepali calendar has four seasons, just like Europe’s.', why: 'It has six, from Basanta to Shishir.' },
    ne: { s: 'नेपाली पात्रोमा युरोपजस्तै चारवटा ऋतु मात्र हुन्छन्।', why: 'छवटा हुन्छन्, वसन्तदेखि शिशिरसम्म।' },
    mai: { s: 'नेपाली पतरा मे युरोप जकाँ चारिए टा ऋतु होइत अछि।', why: 'छह टा होइत अछि, वसन्त सँ शिशिर धरि।' },
  },
  {
    id: 'flower',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'The rhododendron, lali gurans, is Nepal’s national flower.', why: 'In spring it turns whole hillsides red.' },
    ne: { s: 'लालीगुराँस नेपालको राष्ट्रिय फूल हो।', why: 'वसन्तमा यसले पूरै डाँडा रातो बनाउँछ।' },
    mai: { s: 'लालीगुराँस नेपालक राष्ट्रीय फूल अछि।', why: 'वसन्त मे ई पूरा पहाड़ के लाल कऽ दैत अछि।' },
  },
  {
    id: 'lotus',
    truth: false,
    level: 1,
    topic: 'nepal',
    en: { s: 'Nepal’s national flower is the lotus.', why: 'It is the rhododendron, lali gurans.' },
    ne: { s: 'नेपालको राष्ट्रिय फूल कमल हो।', why: 'राष्ट्रिय फूल लालीगुराँस हो।' },
    mai: { s: 'नेपालक राष्ट्रीय फूल कमल अछि।', why: 'राष्ट्रीय फूल लालीगुराँस अछि।' },
  },
  {
    id: 'dashain-kites',
    truth: true,
    level: 1,
    topic: 'nepal',
    en: { s: 'During Dashain, the skies of Nepal fill with kites.', why: 'Kite fights are a Dashain tradition. Try Changa Chet in this arcade.' },
    ne: { s: 'दशैँमा नेपालको आकाश चङ्गाले भरिन्छ।', why: 'चङ्गा चेट दशैँको परम्परा हो। यही आर्केडमा खेलेर हेर्नुहोस्।' },
    mai: { s: 'दशैं मे नेपालक अकास चङ्गा सँ भरि जाइत अछि।', why: 'चङ्गा चेट दशैंक परम्परा थिक। एही आर्केड मे खेलि कऽ देखू।' },
  },
  {
    id: 'tihar-kites',
    truth: false,
    level: 1,
    topic: 'nepal',
    en: { s: 'Tihar is Nepal’s festival of kite flying.', why: 'Kites belong to Dashain. Tihar is the festival of diyo lamps and Laxmi Puja.' },
    ne: { s: 'तिहार नेपालमा चङ्गा उडाउने पर्व हो।', why: 'चङ्गा दशैँमा उडाइन्छ। तिहार दियो र लक्ष्मी पूजाको पर्व हो।' },
    mai: { s: 'तिहार नेपाल मे चङ्गा उड़ाबय बला पाबनि अछि।', why: 'चङ्गा दशैं मे उड़ाओल जाइत अछि। तिहार दीप आ लक्ष्मी पूजाक पाबनि थिक।' },
  },
  {
    id: 'janaki-1910',
    truth: true,
    level: 1,
    topic: 'janakpur',
    en: { s: 'Janaki Mandir in Janakpur was completed in 1910.', why: 'It cost nine lakh, which gave it the name Nau Lakha Mandir.' },
    ne: { s: 'जनकपुरको जानकी मन्दिर सन् १९१० मा बनेर सकिएको हो।', why: 'नौ लाख लागत भएकाले यसलाई नौलखा मन्दिर पनि भनिन्छ।' },
    mai: { s: 'जनकपुरक जानकी मन्दिर सन् १९१० मे बनि कऽ तैयार भेल।', why: 'नौ लाख खर्च भेलाक कारण एकरा नौलखा मन्दिर सेहो कहल जाइत अछि।' },
  },
  {
    id: 'janaki-mughal',
    truth: false,
    level: 2,
    topic: 'janakpur',
    en: { s: 'Janaki Mandir was built by the Mughals in 1610.', why: 'It was commissioned by Queen Vrisha Bhanu of Tikamgarh and completed in 1910.' },
    ne: { s: 'जानकी मन्दिर मुगलहरूले सन् १६१० मा बनाएका हुन्।', why: 'यो टीकमगढकी रानी वृषभानुले बनाउन लगाएको मन्दिर हो, सन् १९१० मा पूरा भयो।' },
    mai: { s: 'जानकी मन्दिर मुगल सभ सन् १६१० मे बनौलक।', why: 'एकरा टीकमगढ़क रानी वृषभानु बनबौलनि, सन् १९१० मे पूरा भेल।' },
  },
  {
    id: 'ponds',
    truth: true,
    level: 1,
    topic: 'janakpur',
    en: { s: 'Janakpur is a city of ponds, with more than 200 sacred ones.', why: 'Dhanush Sagar and Ganga Sagar are the famous two.' },
    ne: { s: 'जनकपुर पोखरीहरूको सहर हो, यहाँ २०० भन्दा बढी पवित्र पोखरी छन्।', why: 'धनुषसागर र गंगासागर सबैभन्दा चर्चित हुन्।' },
    mai: { s: 'जनकपुर पोखरि सभक नगर अछि, एतय २०० सँ बेसी पवित्र पोखरि अछि।', why: 'धनुषसागर आ गंगासागर सभ सँ प्रसिद्ध अछि।' },
  },
  {
    id: 'tirhuta',
    truth: true,
    level: 1,
    topic: 'janakpur',
    en: { s: 'Maithili has its own script, Tirhuta, also called Mithilakshar.', why: 'Today Maithili is mostly written in Devanagari, but Tirhuta is its very own.' },
    ne: { s: 'मैथिली भाषाको आफ्नै लिपि छ: तिरहुता, जसलाई मिथिलाक्षर पनि भनिन्छ।', why: 'आजकल मैथिली प्रायः देवनागरीमा लेखिन्छ, तर तिरहुता यसको आफ्नै लिपि हो।' },
    mai: { s: 'मैथिलीक अपन लिपि अछि: तिरहुता, जकरा मिथिलाक्षर सेहो कहल जाइत अछि।', why: 'आइकाल्हि मैथिली बेसीकाल देवनागरी मे लिखल जाइत अछि, मुदा तिरहुता एकर अपन लिपि थिक।' },
  },
  {
    id: 'maithili-latin',
    truth: false,
    level: 2,
    topic: 'janakpur',
    en: { s: 'Maithili has only ever been written in the Latin alphabet.', why: 'It is written in Devanagari today, and historically in its own Tirhuta script.' },
    ne: { s: 'मैथिली सधैँ ल्याटिन वर्णमालामा मात्र लेखिँदै आएको छ।', why: 'आज देवनागरीमा लेखिन्छ, र ऐतिहासिक रूपमा आफ्नै तिरहुता लिपिमा।' },
    mai: { s: 'मैथिली सदिखन खाली लैटिन वर्णमाला मे लिखल गेल अछि।', why: 'आइ देवनागरी मे लिखल जाइत अछि, आ इतिहास मे अपन तिरहुता लिपि मे।' },
  },
  {
    id: 'chhath',
    truth: true,
    level: 2,
    topic: 'janakpur',
    en: { s: 'Chhath, with offerings to the sun at ponds, is the biggest festival in Janakpur.', why: 'The ponds fill with devotees at sunset, and again at sunrise.' },
    ne: { s: 'पोखरीमा सूर्यलाई अर्घ्य दिइने छठ जनकपुरको सबैभन्दा ठूलो पर्व हो।', why: 'साँझ र फेरि बिहान सूर्योदयमा पोखरीहरू भक्तजनले भरिन्छन्।' },
    mai: { s: 'पोखरि मे सूर्य के अर्घ देल जाय बला छठ जनकपुरक सभ सँ पैघ पाबनि अछि।', why: 'साँझ आ फेर भोरे सूर्योदय मे पोखरि सभ भक्त सँ भरि जाइत अछि।' },
  },
  {
    id: 'vivah',
    truth: true,
    level: 2,
    topic: 'janakpur',
    en: { s: 'Every year at Vivah Panchami, Janakpur re-enacts the wedding of Ram and Sita.', why: 'Janakpur is Sita’s birthplace, so it plays the bride’s side of the story.' },
    ne: { s: 'जनकपुरमा हरेक वर्ष विवाह पञ्चमीमा राम र सीताको विवाह मञ्चन गरिन्छ।', why: 'जनकपुर सीताको जन्मथलो हो, त्यसैले यो कथामा दुलहीपक्ष हो।' },
    mai: { s: 'जनकपुर मे सभ साल विवाह पञ्चमी मे राम आ सीताक बियाह मंचन कएल जाइत अछि।', why: 'जनकपुर सीताक जन्मभूमि थिक, तेँ एहि कथा मे ई कनियाँ पक्ष थिक।' },
  },
  {
    id: 'mithila-painting',
    truth: false,
    level: 3,
    topic: 'janakpur',
    en: { s: 'Mithila paintings are known for single thin outlines and empty backgrounds.', why: 'Double outlines and dense kachni line work are the signature, with fish, peacocks, lotus and sun.' },
    ne: { s: 'मिथिला चित्रकला एकल पातलो रेखा र खाली पृष्ठभूमिका लागि चिनिन्छ।', why: 'दोहोरो रेखा र घना कचनी शैली यसको पहिचान हो, माछा, मयूर, कमल र सूर्यसहित।' },
    mai: { s: 'मिथिला चित्रकला एकहरा पातर रेखा आ खाली पृष्ठभूमि लेल जानल जाइत अछि।', why: 'दोहरा रेखा आ घन कचनी शैली एकर पहिचान थिक, माछ, मयूर, कमल आ सूर्य संग।' },
  },
  {
    id: 'jkr-elevation',
    truth: false,
    level: 2,
    topic: 'janakpur',
    en: { s: 'Janakpur sits high in the Himalaya, at about 3,000 m.', why: 'It is down in the flat Terai: the airport is just 78 m above sea level.' },
    ne: { s: 'जनकपुर हिमालयमा करिब ३,००० मिटर उचाइमा छ।', why: 'यो समथर तराईमा छ: विमानस्थल समुद्री सतहबाट ७८ मिटर मात्र माथि छ।' },
    mai: { s: 'जनकपुर हिमालय मे करीब ३,००० मिटर ऊँचाइ पर अछि।', why: 'ई समतल तराई मे अछि: विमानस्थल समुद्र सतह सँ मात्र ७८ मिटर ऊपर अछि।' },
  },
  {
    id: 'jkr-icao',
    truth: true,
    level: 2,
    topic: 'aviation',
    en: { s: 'Janakpur Airport’s ICAO code is VNJP.', why: 'Its IATA code is JKR. Every ICAO code in Nepal starts with VN.' },
    ne: { s: 'जनकपुर विमानस्थलको ICAO कोड VNJP हो।', why: 'यसको IATA कोड JKR हो। नेपालका सबै ICAO कोड VN बाट सुरु हुन्छन्।' },
    mai: { s: 'जनकपुर विमानस्थलक ICAO कोड VNJP अछि।', why: 'एकर IATA कोड JKR अछि। नेपालक सभ ICAO कोड VN सँ शुरू होइत अछि।' },
  },
  {
    id: 'jkr-iata',
    truth: false,
    level: 2,
    topic: 'aviation',
    en: { s: 'Janakpur Airport’s IATA code is JNK.', why: 'It is JKR. Its ICAO code is VNJP.' },
    ne: { s: 'जनकपुर विमानस्थलको IATA कोड JNK हो।', why: 'JKR हो। ICAO कोड चाहिँ VNJP हो।' },
    mai: { s: 'जनकपुर विमानस्थलक IATA कोड JNK अछि।', why: 'JKR अछि। ICAO कोड VNJP अछि।' },
  },
  {
    id: 'jkr-runway',
    truth: true,
    level: 2,
    topic: 'aviation',
    en: { s: 'Janakpur Airport has one runway, 09/27, about 1,300 m long.', why: 'Runway numbers are headings divided by ten: 09 faces east, 27 faces west.' },
    ne: { s: 'जनकपुर विमानस्थलमा एउटा मात्र धावनमार्ग छ, 09/27, करिब १,३०० मिटर लामो।', why: 'धावनमार्गको नम्बर दिशालाई दसले भाग गरेर बन्छ: 09 पूर्वतिर, 27 पश्चिमतिर।' },
    mai: { s: 'जनकपुर विमानस्थल मे एकेटा धावनमार्ग अछि, 09/27, करीब १,३०० मिटर नमहर।', why: 'धावनमार्गक नम्बर दिशा के दस सँ भाग दऽ कऽ बनैत अछि: 09 पूब दिस, 27 पच्छिम दिस।' },
  },
  {
    id: 'jkr-jumbo',
    truth: false,
    level: 2,
    topic: 'aviation',
    en: { s: 'Janakpur’s runway is 3,000 m long, built for jumbo jets.', why: 'It is about 1,300 m by 30 m, sized for small turboprops.' },
    ne: { s: 'जनकपुरको धावनमार्ग जम्बो जेटका लागि बनाइएको ३,००० मिटर लामो छ।', why: 'यो करिब १,३०० मिटर लामो र ३० मिटर चौडा छ, साना टर्बोप्रप विमानका लागि।' },
    mai: { s: 'जनकपुरक धावनमार्ग जम्बो जेट लेल बनल ३,००० मिटर नमहर अछि।', why: 'ई करीब १,३०० मिटर नमहर आ ३० मिटर चाकर अछि, छोट टर्बोप्रप विमान लेल।' },
  },
  {
    id: 'lights',
    truth: true,
    level: 2,
    topic: 'aviation',
    en: { s: 'An aircraft carries a red light on its left (port) wing and a green one on its right.', why: 'At night, pilots can tell which way another plane is heading from the colours.' },
    ne: { s: 'विमानको देब्रे (पोर्ट) पखेटामा रातो र दाहिनेमा हरियो बत्ती हुन्छ।', why: 'रातमा अर्को विमान कता जाँदैछ भनेर पाइलटले यही रङबाट थाहा पाउँछन्।' },
    mai: { s: 'विमानक बामा (पोर्ट) पाँखि पर लाल आ दहिना पर हरियर बत्ती रहैत अछि।', why: 'राति मे दोसर विमान कोन दिस जा रहल अछि, से पायलट एही रंग सँ बुझैत छथि।' },
  },
  {
    id: 'lights-swap',
    truth: false,
    level: 3,
    topic: 'aviation',
    en: { s: 'An aircraft’s green navigation light is on its left (port) wing.', why: 'Green is on the right (starboard). Red is port, on the left.' },
    ne: { s: 'विमानको हरियो नेभिगेसन बत्ती देब्रे (पोर्ट) पखेटामा हुन्छ।', why: 'हरियो दाहिने (स्टारबोर्ड) मा हुन्छ। रातो देब्रे, पोर्टमा।' },
    mai: { s: 'विमानक हरियर नेभिगेशन बत्ती बामा (पोर्ट) पाँखि पर रहैत अछि।', why: 'हरियर दहिना (स्टारबोर्ड) पर रहैत अछि। लाल बामा, पोर्ट पर।' },
  },
  {
    id: 'evtol',
    truth: true,
    level: 1,
    topic: 'aviation',
    en: { s: 'An eVTOL is an electric aircraft that takes off and lands vertically.', why: 'Electric Vertical Take-Off and Landing. Shuvam’s ongoing research is air traffic control for them.' },
    ne: { s: 'eVTOL ठाडो उडान र अवतरण गर्ने, बिजुलीले चल्ने विमान हो।', why: 'Electric Vertical Take-Off and Landing। शुभमको चलिरहेको अनुसन्धान यिनैका लागि एयर ट्राफिक कन्ट्रोल हो।' },
    mai: { s: 'eVTOL ठाढ़ उड़ान आ अवतरण करय बला, बिजली सँ चलय बला विमान थिक।', why: 'Electric Vertical Take-Off and Landing। शुभमक चलि रहल शोध एकरे लेल एयर ट्राफिक कन्ट्रोल थिक।' },
  },
  {
    id: 'evtol-runway',
    truth: false,
    level: 1,
    topic: 'aviation',
    en: { s: 'eVTOLs need a long runway to take off.', why: 'VTOL means vertical takeoff and landing. A rooftop pad is enough.' },
    ne: { s: 'eVTOL लाई उड्न लामो धावनमार्ग चाहिन्छ।', why: 'VTOL को अर्थ ठाडो उडान र अवतरण हो। छतमाथिको प्याड नै पुग्छ।' },
    mai: { s: 'eVTOL के उड़बाक लेल नमहर धावनमार्ग चाही।', why: 'VTOL माने ठाढ़ उड़ान आ अवतरण। छत परक प्याड पर्याप्त अछि।' },
  },
  {
    id: 'rag',
    truth: true,
    level: 1,
    topic: 'ai',
    en: { s: 'RAG stands for retrieval-augmented generation.', why: 'The model looks up evidence first, then writes with it.' },
    ne: { s: 'RAG को पूरा रूप retrieval-augmented generation हो।', why: 'मोडलले पहिले प्रमाण खोज्छ, अनि त्यसैको आधारमा लेख्छ।' },
    mai: { s: 'RAG क पूरा रूप retrieval-augmented generation अछि।', why: 'मॉडल पहिने प्रमाण तकैत अछि, तखन ओकरे आधार पर लिखैत अछि।' },
  },
  {
    id: 'rag-retrain',
    truth: false,
    level: 2,
    topic: 'ai',
    en: { s: 'RAG means the model retrains itself on every question.', why: 'No training happens: RAG retrieves documents and adds them to the prompt.' },
    ne: { s: 'RAG भनेको मोडलले हरेक प्रश्नमा आफैँलाई फेरि तालिम दिनु हो।', why: 'कुनै तालिम हुँदैन: RAG ले कागजात खोजेर प्रम्प्टमा थप्छ।' },
    mai: { s: 'RAG माने मॉडल सभ प्रश्न पर अपना के फेर सँ ट्रेन करैत अछि।', why: 'कोनो ट्रेनिंग नहि होइत अछि: RAG दस्तावेज तकि कऽ प्रम्प्ट मे जोड़ैत अछि।' },
  },
  {
    id: 'lora',
    truth: true,
    level: 2,
    topic: 'ai',
    en: { s: 'LoRA fine-tunes a model by training small low-rank matrices instead of all its weights.', why: 'Low-Rank Adaptation: cheap enough for a consumer GPU, which is why the Bio-Memory paper uses it.' },
    ne: { s: 'LoRA ले सबै वेटको सट्टा साना low-rank म्याट्रिक्स मात्र तालिम दिएर मोडल फाइन-ट्युन गर्छ।', why: 'Low-Rank Adaptation: साधारण GPU मै चल्ने सस्तो तरिका, त्यसैले Bio-Memory पेपरले यही प्रयोग गर्छ।' },
    mai: { s: 'LoRA सभ वेटक बदला छोट low-rank म्याट्रिक्स मात्र ट्रेन कऽ कऽ मॉडल के फाइन-ट्यून करैत अछि।', why: 'Low-Rank Adaptation: साधारण GPU पर चलय जोग सस्त तरीका, तेँ Bio-Memory पेपर एकरे प्रयोग करैत अछि।' },
  },
  {
    id: 'lora-long',
    truth: false,
    level: 2,
    topic: 'ai',
    en: { s: 'LoRA stands for Long Range Attention.', why: 'It is Low-Rank Adaptation, a way to fine-tune big models cheaply.' },
    ne: { s: 'LoRA को पूरा रूप Long Range Attention हो।', why: 'यो Low-Rank Adaptation हो, ठूला मोडललाई सस्तोमा फाइन-ट्युन गर्ने तरिका।' },
    mai: { s: 'LoRA क पूरा रूप Long Range Attention अछि।', why: 'ई Low-Rank Adaptation थिक, पैघ मॉडल के सस्त मे फाइन-ट्यून करबाक तरीका।' },
  },
  {
    id: 'fl',
    truth: true,
    level: 2,
    topic: 'ai',
    en: { s: 'In federated learning, raw data stays on each device and only model updates are shared.', why: 'The model travels to the data, not the other way round.' },
    ne: { s: 'फेडेरेटेड लर्निङमा कच्चा डेटा आफ्नै डिभाइसमा रहन्छ, मोडलका अपडेट मात्र साझा हुन्छन्।', why: 'डेटा मोडलतिर होइन, मोडल डेटातिर जान्छ।' },
    mai: { s: 'फेडरेटेड लर्निंग मे कच्चा डेटा अपने डिवाइस पर रहैत अछि, खाली मॉडलक अपडेट साझा होइत अछि।', why: 'डेटा मॉडल लग नहि, मॉडल डेटा लग जाइत अछि।' },
  },
  {
    id: 'fl-upload',
    truth: false,
    level: 2,
    topic: 'ai',
    en: { s: 'Federated learning works by uploading everyone’s raw data to one big server.', why: 'That is exactly what it avoids. Only model updates leave the device.' },
    ne: { s: 'फेडेरेटेड लर्निङले सबैको कच्चा डेटा एउटै ठूलो सर्भरमा अपलोड गरेर काम गर्छ।', why: 'ठ्याक्कै त्यही कुरा यसले रोक्छ। डिभाइसबाट मोडल अपडेट मात्र बाहिर जान्छ।' },
    mai: { s: 'फेडरेटेड लर्निंग सभक कच्चा डेटा एकटा पैघ सर्भर पर अपलोड कऽ कऽ काज करैत अछि।', why: 'ठीक एही बात सँ ई बचैत अछि। डिवाइस सँ खाली मॉडल अपडेट बाहर जाइत अछि।' },
  },
  {
    id: 'ebbinghaus',
    truth: false,
    level: 2,
    topic: 'ai',
    en: { s: 'The Ebbinghaus forgetting curve says memories get stronger the longer you ignore them.', why: 'Memories fade with time. Each well-timed recall makes them last longer.' },
    ne: { s: 'एबिङहाउसको बिर्सने वक्रअनुसार सम्झनालाई जति बेवास्ता गर्यो, त्यति बलियो हुन्छ।', why: 'सम्झना समयसँगै धमिलिन्छ। ठीक समयमा सम्झँदा लामो टिक्छ।' },
    mai: { s: 'एबिंगहॉसक बिसरबाक वक्र कहैत अछि जे स्मृति के जतेक अनदेखा करब, ओतेक मजगूत होएत।', why: 'स्मृति समयक संग फीका होइत अछि। ठीक समय पर मोन पाड़ला सँ बेसी दिन टिकैत अछि।' },
  },
  {
    id: 'hallucination-def',
    truth: false,
    level: 1,
    topic: 'ai',
    en: { s: 'An AI hallucination is when the model says “I do not know”.', why: 'That is the honest answer. A hallucination is a confident, false claim.' },
    ne: { s: 'AI ले “मलाई थाहा छैन” भन्नु नै हलुसिनेसन हो।', why: 'त्यो त इमानदार उत्तर हो। हलुसिनेसन भनेको आत्मविश्वासका साथ भनिएको झूटो दाबी हो।' },
    mai: { s: 'AI जखन “हमरा नहि बुझल अछि” कहैत अछि, सैह हलुसिनेसन थिक।', why: 'ओ तँ इमानदार उत्तर थिक। हलुसिनेसन माने पूरा भरोसा संग कहल गेल झूठ दाबी।' },
  },
  {
    id: 'born',
    truth: false,
    level: 1,
    topic: 'shuvam',
    en: { s: 'Shuvam was born in Kathmandu.', why: 'He was born in Janakpur Dham, Sita’s city, and now lives in Lalitpur.' },
    ne: { s: 'शुभमको जन्म काठमाडौँमा भएको हो।', why: 'उनको जन्म सीताको सहर जनकपुरधाममा भएको हो, अहिले उनी ललितपुरमा बस्छन्।' },
    mai: { s: 'शुभमक जन्म काठमाडौं मे भेल छलनि।', why: 'हुनक जन्म सीताक नगर जनकपुरधाम मे भेलनि, एखन ओ ललितपुर मे रहैत छथि।' },
  },
  {
    id: 'flight-number',
    truth: true,
    level: 1,
    topic: 'shuvam',
    en: { s: 'This site’s flight number, SS2504, comes from Shuvam’s birthday, 25 April.', why: 'SS for Shuvam Singh, 2504 for 25 April 2003.' },
    ne: { s: 'यो साइटको उडान नम्बर SS2504 शुभमको जन्मदिन, २५ अप्रिलबाट आएको हो।', why: 'SS भनेको शुभम सिंह, 2504 भनेको २५ अप्रिल २००३।' },
    mai: { s: 'एहि साइटक उड़ान नम्बर SS2504 शुभमक जन्मदिन, २५ अप्रिल सँ आएल अछि।', why: 'SS माने शुभम सिंह, 2504 माने २५ अप्रिल २००३।' },
  },
  {
    id: 'mother-tongue',
    truth: true,
    level: 1,
    topic: 'shuvam',
    en: { s: 'Shuvam’s mother tongue is Maithili.', why: 'He also speaks Nepali and English, which is why this site comes in all three.' },
    ne: { s: 'शुभमको मातृभाषा मैथिली हो।', why: 'उनी नेपाली र अंग्रेजी पनि बोल्छन्, त्यसैले यो साइट तीनै भाषामा छ।' },
    mai: { s: 'शुभमक मातृभाषा मैथिली अछि।', why: 'ओ नेपाली आ अंग्रेजी सेहो बजैत छथि, तेँ ई साइट तीनू भाषा मे अछि।' },
  },
  {
    id: 'srm-chennai',
    truth: false,
    level: 2,
    topic: 'shuvam',
    en: { s: 'Shuvam studied computer science at SRM’s campus in Chennai.', why: 'It was SRM University: B.Tech CSE (Big Data), 2022 to 2026.' },
    ne: { s: 'शुभमले चेन्नईस्थित SRM क्याम्पसमा कम्प्युटर विज्ञान पढे।', why: 'उनले SRM University मा पढे: B.Tech CSE (Big Data), २०२२ देखि २०२६।' },
    mai: { s: 'शुभम चेन्नई स्थित SRM क्याम्पस मे कम्प्यूटर विज्ञान पढ़लनि।', why: 'ओ SRM University मे पढ़लनि: B.Tech CSE (Big Data), २०२२ सँ २०२६।' },
  },
  {
    id: 'ielts',
    truth: false,
    level: 2,
    topic: 'shuvam',
    en: { s: 'Shuvam scored a perfect 9.0 in IELTS.', why: 'It was 7.5. Still a self-certified professional yapper, in three languages.' },
    ne: { s: 'शुभमले IELTS मा पूरै ९.० ल्याए।', why: '७.५ ल्याएका हुन्। तैपनि तीन भाषामा आफैँले प्रमाणित गरेका पेसेवर गफाडी हुन्।' },
    mai: { s: 'शुभम IELTS मे पूरा ९.० अनलनि।', why: '७.५ अनलनि। तइयो तीन भाषा मे अपने सँ प्रमाणित पेशेवर गपबाज छथि।' },
  },
  {
    id: 'bio-memory',
    truth: true,
    level: 1,
    topic: 'shuvam',
    en: { s: 'Shuvam’s Bio-Memory paper was accepted at IEEE ICAII 2026.', why: 'It mixes an Ebbinghaus forgetting curve, LoRA and sleep-phase consolidation. Memory Keeper is based on it.' },
    ne: { s: 'शुभमको Bio-Memory पेपर IEEE ICAII 2026 मा स्वीकृत भयो।', why: 'यसमा एबिङहाउस वक्र, LoRA र निद्रामा हुने स्मृति सुदृढीकरण छ। Memory Keeper यसैमा आधारित छ।' },
    mai: { s: 'शुभमक Bio-Memory पेपर IEEE ICAII 2026 मे स्वीकृत भेल।', why: 'एहि मे एबिंगहॉस वक्र, LoRA आ निन्न मे होमय बला स्मृति सुदृढ़ीकरण अछि। Memory Keeper एकरे पर आधारित अछि।' },
  },
  {
    id: 'bio-supercomputer',
    truth: false,
    level: 2,
    topic: 'shuvam',
    en: { s: 'The Bio-Memory model needs a supercomputer to run.', why: 'It is designed for consumer-grade GPUs.' },
    ne: { s: 'Bio-Memory मोडल चलाउन सुपरकम्प्युटर चाहिन्छ।', why: 'यो साधारण उपभोक्ता GPU का लागि डिजाइन गरिएको हो।' },
    mai: { s: 'Bio-Memory मॉडल चलाबय लेल सुपरकम्प्यूटर चाही।', why: 'ई साधारण उपभोक्ता GPU लेल डिजाइन कएल गेल अछि।' },
  },
  {
    id: 'seg-203',
    truth: true,
    level: 2,
    topic: 'shuvam',
    en: { s: 'Segmented Generation beat a naive RAG baseline by 203% on a 500-query benchmark.', why: 'It plans a template, then gives every segment its own full context window.' },
    ne: { s: 'Segmented Generation ले ५०० प्रश्नको बेन्चमार्कमा साधारण RAG लाई २०३% ले उछिन्यो।', why: 'यसले पहिले टेम्प्लेट बनाउँछ, अनि हरेक खण्डलाई आफ्नै पूरा कन्टेक्स्ट विन्डो दिन्छ।' },
    mai: { s: 'Segmented Generation ५०० प्रश्नक बेन्चमार्क मे साधारण RAG सँ २०३% आगाँ रहल।', why: 'ई पहिने टेम्प्लेट बनबैत अछि, तखन सभ खण्ड के अपन पूरा कन्टेक्स्ट विन्डो दैत अछि।' },
  },
  {
    id: 'seg-cram',
    truth: false,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Segmented Generation works by cramming the whole document into one giant prompt.', why: 'The opposite: it writes segment by segment, each with a clean, full window.' },
    ne: { s: 'Segmented Generation ले पूरै कागजात एउटै ठूलो प्रम्प्टमा कोचेर काम गर्छ।', why: 'उल्टो: यसले खण्ड खण्ड गरेर लेख्छ, हरेकलाई सफा र पूरा विन्डो दिएर।' },
    mai: { s: 'Segmented Generation पूरा दस्तावेज एकटा पैघ प्रम्प्ट मे ठूसि कऽ काज करैत अछि।', why: 'उनटा: ई खण्ड खण्ड कऽ कऽ लिखैत अछि, सभ के साफ आ पूरा विन्डो दऽ कऽ।' },
  },
  {
    id: 'bus-loophole',
    truth: true,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Shuvam’s smart bus project had no tracking API, so he streamed real coordinates through a Google Maps loophole.', why: 'True, and it was a first-year project, with dynamic pricing on MongoDB Atlas.' },
    ne: { s: 'शुभमको स्मार्ट बस प्रोजेक्टमा ट्र्याकिङ API थिएन, त्यसैले उनले Google Maps को एउटा लुपहोलबाट वास्तविक लोकेसन पठाए।', why: 'साँचो हो, र यो MongoDB Atlas मा डाइनामिक भाडासहितको पहिलो वर्षको प्रोजेक्ट थियो।' },
    mai: { s: 'शुभमक स्मार्ट बस प्रोजेक्ट मे ट्र्याकिंग API नहि छल, तेँ ओ Google Maps क एकटा लूपहोल सँ असली लोकेशन पठौलनि।', why: 'सत्य, आ ई MongoDB Atlas पर डायनामिक भाड़ा बला पहिल सालक प्रोजेक्ट छल।' },
  },
  {
    id: 'bus-paid',
    truth: false,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Shuvam’s smart bus project ran on a paid real-time bus tracking API.', why: 'There was no tracking API at all. He streamed real coordinates through a Google Maps loophole.' },
    ne: { s: 'शुभमको स्मार्ट बस प्रोजेक्ट सशुल्क रियल टाइम बस ट्र्याकिङ API मा चल्थ्यो।', why: 'कुनै ट्र्याकिङ API नै थिएन। उनले Google Maps को लुपहोलबाट वास्तविक लोकेसन पठाए।' },
    mai: { s: 'शुभमक स्मार्ट बस प्रोजेक्ट पाइ लागय बला रियल टाइम बस ट्र्याकिंग API पर चलैत छल।', why: 'कोनो ट्र्याकिंग API छलहे नहि। ओ Google Maps क लूपहोल सँ असली लोकेशन पठौलनि।' },
  },
  {
    id: 'icaast',
    truth: true,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Shuvam’s ICAAsT 2024 paper is about 4D trajectory conflict detection in air traffic.', why: '4D means position plus time: where every flight will be, and when. UAM Tower plays with the idea.' },
    ne: { s: 'शुभमको ICAAsT 2024 पेपर हवाई यातायातमा 4D ट्राजेक्टोरी द्वन्द्व पत्ता लगाउने विषयमा हो।', why: '4D भनेको स्थान र समय: हरेक उडान कहाँ र कहिले हुन्छ। UAM Tower यही विचारसँग खेल्छ।' },
    mai: { s: 'शुभमक ICAAsT 2024 पेपर हवाई यातायात मे 4D ट्राजेक्टरी टकराव पता लगेबाक विषय पर अछि।', why: '4D माने स्थान आ समय: सभ उड़ान कतय आ कखन रहत। UAM Tower एही विचार सँ खेलैत अछि।' },
  },
  {
    id: 'elser',
    truth: true,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Shuvam’s Elser engine represents language with units called Psifi, Psif, Sif and Keno.', why: 'A symbolic alternative to token embeddings. Yes, those names are real.' },
    ne: { s: 'शुभमको Elser इन्जिनले भाषालाई Psifi, Psif, Sif र Keno नामका एकाइमा प्रस्तुत गर्छ।', why: 'टोकन एम्बेडिङको प्रतीकात्मक विकल्प। हो, यी नाम साँच्चै हुन्।' },
    mai: { s: 'शुभमक Elser इंजन भाषा के Psifi, Psif, Sif आ Keno नामक इकाई मे प्रस्तुत करैत अछि।', why: 'टोकन एम्बेडिंगक प्रतीकात्मक विकल्प। हँ, ई नाम सत्ते अछि।' },
  },
  {
    id: 'elser-fake',
    truth: false,
    level: 3,
    topic: 'shuvam',
    en: { s: 'Shuvam’s Elser engine is built on a 70-billion-parameter transformer.', why: 'Elser is symbolic: it composes compact Psifi, Psif, Sif and Keno units instead of giant embeddings.' },
    ne: { s: 'शुभमको Elser इन्जिन ७० अर्ब प्यारामिटरको ट्रान्सफर्मरमा बनेको छ।', why: 'Elser प्रतीकात्मक हो: यसले ठूला एम्बेडिङको सट्टा साना Psifi, Psif, Sif र Keno एकाइ जोड्छ।' },
    mai: { s: 'शुभमक Elser इंजन ७० अरब प्यारामीटरक ट्रान्सफॉर्मर पर बनल अछि।', why: 'Elser प्रतीकात्मक अछि: ई पैघ एम्बेडिंगक बदला छोट Psifi, Psif, Sif आ Keno इकाई जोड़ैत अछि।' },
  },
];

export const factText = (fact, lang) => fact[lang] || fact.en;
